/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planilla_atsbcr.vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author larguedas
 */
public class PlanillaSemanal extends javax.swing.JFrame {

    /**
     * Creates new form PlanillaSemanal
     */
    public PlanillaSemanal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIDEmp = new javax.swing.JLabel();
        jTextIdEmp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelNombEmp = new javax.swing.JLabel();
        jTextNombreEmp = new javax.swing.JTextField();
        jLabelApellido02 = new javax.swing.JLabel();
        jTextApellido02 = new javax.swing.JTextField();
        jLabelApellido01 = new javax.swing.JLabel();
        jTextApellido01 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDesglose = new javax.swing.JTable();
        jLabelpuesto = new javax.swing.JLabel();
        jTextpuesto = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planilla Semanal");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Planilla semanal");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelIDEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIDEmp.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIDEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIDEmp.setText("ID Empleado:");

        jTextIdEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextIdEmp.setForeground(new java.awt.Color(0, 0, 0));
        jTextIdEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextIdEmp.setToolTipText("Ingrese Cedula del Empleado");
        jTextIdEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextIdEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdEmpActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelNombEmp.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNombEmp.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombEmp.setText("Nombre del Empleado:");

        jTextNombreEmp.setEditable(false);
        jTextNombreEmp.setBackground(new java.awt.Color(255, 255, 255));
        jTextNombreEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextNombreEmp.setForeground(new java.awt.Color(0, 0, 153));
        jTextNombreEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNombreEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelApellido02.setBackground(new java.awt.Color(255, 255, 255));
        jLabelApellido02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelApellido02.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApellido02.setText("Apellido Materno:");

        jTextApellido02.setEditable(false);
        jTextApellido02.setBackground(new java.awt.Color(255, 255, 255));
        jTextApellido02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextApellido02.setForeground(new java.awt.Color(0, 0, 153));
        jTextApellido02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextApellido02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelApellido01.setBackground(new java.awt.Color(255, 255, 255));
        jLabelApellido01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelApellido01.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApellido01.setText("Apellido Paterno:");

        jTextApellido01.setEditable(false);
        jTextApellido01.setBackground(new java.awt.Color(255, 255, 255));
        jTextApellido01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextApellido01.setForeground(new java.awt.Color(0, 0, 153));
        jTextApellido01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextApellido01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setToolTipText("");
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTableDesglose.setAutoCreateRowSorter(true);
        jTableDesglose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableDesglose.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Horas Diurnas", null, null, null},
                {"Horas Mixtas", null, null, null},
                {"Horas Nocturnas", null, null, null},
                {"Horas Extras Diurnas", null, null, null},
                {"Horas Extras Mixtas", null, null, null},
                {"Horas Extra Nocturnas", null, null, null},
                {"Horas Feriados Pagos", null, null, null},
                {"Bonos y Vacaciones", null, null, null},
                {"Total Bruto", null, null, null},
                {"DEDUCCIONES", null, null, null},
                {"C.C.S.S", null, null, null},
                {"Renta", null, null, null},
                {"Embargos", null, null, null},
                {"Otros", null, null, null},
                {"Salario Neto", null, null, null},
                {"Pago Mediante Trasferencias", null, null, null},
                {"Pago en Efectivo", null, null, null}
            },
            new String [] {
                "Desglose de Horas", "Valor por hora", "Horas Laboradas", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDesglose.setToolTipText("Ingrese los valores Generados por el Empleado");
        jTableDesglose.setRowHeight(25);
        jTableDesglose.setRowMargin(10);
        jTableDesglose.setShowHorizontalLines(true);
        jTableDesglose.setShowVerticalLines(true);
        jScrollPane2.setViewportView(jTableDesglose);

        jLabelpuesto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelpuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelpuesto.setForeground(new java.awt.Color(0, 0, 0));
        jLabelpuesto.setText("Puesto:");

        jTextpuesto.setEditable(false);
        jTextpuesto.setBackground(new java.awt.Color(255, 255, 255));
        jTextpuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextpuesto.setForeground(new java.awt.Color(0, 0, 153));
        jTextpuesto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelIDEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(157, 157, 157)
                                    .addComponent(jTextNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextApellido02, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelApellido02)
                                .addComponent(jLabelNombEmp)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelpuesto)
                            .addComponent(jLabelApellido01))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextApellido01, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDEmp)
                    .addComponent(jTextIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombEmp)
                    .addComponent(jTextNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido01)
                    .addComponent(jTextApellido01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextApellido02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelpuesto)
                        .addComponent(jTextpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelApellido02))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIdEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdEmpActionPerformed
        //Ingreso Cedula Empleado:
        
    }//GEN-LAST:event_jTextIdEmpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Validacion de cedula:
        if(jTextIdEmp.getText().trim().length()==0){
            JOptionPane.showMessageDialog(null, "Ingrese la cedula del Empleado"," Valor Faltante", HEIGHT);
        }else{
            JOptionPane.showMessageDialog(jLabelIDEmp, "Funciona");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanillaSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanillaSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanillaSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanillaSemanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanillaSemanal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido01;
    private javax.swing.JLabel jLabelApellido02;
    private javax.swing.JLabel jLabelIDEmp;
    private javax.swing.JLabel jLabelNombEmp;
    private javax.swing.JLabel jLabelpuesto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDesglose;
    private javax.swing.JTextField jTextApellido01;
    private javax.swing.JTextField jTextApellido02;
    private javax.swing.JTextField jTextIdEmp;
    private javax.swing.JTextField jTextNombreEmp;
    private javax.swing.JTextField jTextpuesto;
    // End of variables declaration//GEN-END:variables
}
